config/routes.rb
Rails.application.routes.draw do

  resources :wikis
  resources :charges, only: [:new, :create]

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaborations
  has_many :users, through: :collaborations

  has_many :wikis

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborations
  has_many :users, through: :collaborations

  belongs_to :user 
  
  scope :private_wikis, -> { where private: true }
  scope :owned_wikis, lambda { |user| where(:user_id => user.id) }
  scope :public_wikis, -> { where private: false }
  scope :show_wiki_details, lambda { |wiki_id| Wiki.where(id: wiki_id) }

  def self.is_wiki_collaborator(user, wiki_id)
    wiki_list = []
    user.collaborations.each { |wiki|  wiki_list << wiki.wiki_id }
    wiki_list.include? wiki_id 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to wikis_path, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    wikis_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :is_premium_user
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_filter :authenticate_user!

  def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  current_user.is_premium_user = true
  current_user.save

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: 9_000_000_000_00
    }

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  def index
    @public_wikis = Wiki.public_wikis
    @private_wikis = Wiki.private_wikis.owned_wikis(get_current_user) if user_signed_in?
    @collaboration_wikis = Wiki.show_wiki_details(get_list_of_wikis_being_collaborated) if user_signed_in?

  @number_of_wiki_collorations = is_wiki_collaborator? 8
  # @wikis = policy_cope(Wiki)
  @wikis = Wiki.all

  end

  def show
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user_id = current_user.id
    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
    authorize @wiki
  end

  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id,  user_ids: [])
    end

    def get_current_user
      if current_user == nil
        return nil 
      else
        current_user
      end
    end

    def get_list_of_wikis_being_collaborated
      if current_user == nil
        return nil 
      else
        current_user.collaborations.pluck(:wiki_id)
      end
    end

    def is_wiki_collaborator? (wiki_id)
      wiki_list = []
      current_user.collaborations.each { |wiki|  wiki_list << wiki.wiki_id } if user_signed_in?
      wiki_list.include? wiki_id 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!-- jQuery is used only for this example; it isn't required to use Stripe -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<!-- The required Stripe lib -->
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
// This identifies your website in the createToken call below
Stripe.setPublishableKey('pk_test_4Y4UU2GvSP2STewjDaGQoxCG');

var stripeResponseHandler = function(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // token contains id, last4, and card type
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and re-submit
    $form.get(0).submit();
  }
};

jQuery(function($) {
  $('#payment-form').submit(function(e) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});
</script>

<%= form_tag charges_path, method: 'post', id: 'payment-form'  do %>
  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>
  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>
  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input id='exp-month' type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input id='exp-year' type="text" size="4" data-stripe="exp-year"/>
  </div>
  
  <%= submit_tag("Charge my card") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="container-fluid">
      <div class ="row">
        <div class="col-md-4 pull-right">
          <% if user_signed_in? %>
            <br />
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path %>
            <br />
            <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12"
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12"
          <%= yield %>
        </div>
    </div>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/welcome/index.html.slim
h1 Blocipedia: Social Markdown Wikis 

p Create and share Markdown Wikis

p Create as many public wikis as you want!

p Create private wikis!

p Free Plan

p Premium Plan

= link_to 'View Public Wikis', wikis_path

app/views/wikis/_form.html.slim
= form_for @wiki do |f|
  - if @wiki.errors.any?
    #error_explanation
      h2 = "#{pluralize(@wiki.errors.count, "error")} prohibited this wiki from being saved:"
      ul
        - @wiki.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    - hidden_field_tag "wiki[user_ids][]", nil
    - User.all.each do |user|
      = check_box_tag "wiki[user_ids][]", user.id, @wiki.user_ids.include?(user.id), id: dom_id(user)
      = label_tag dom_id(user), user.email
      <br />
  .field
    = f.label 'Make wiki private' if current_user.is_premium_user?
    = f.check_box :private if current_user.is_premium_user? 
    = link_to 'Upgrade to premium user to create private wikis', edit_user_registration_path if current_user.is_premium_user == false
  .actions = f.submit 'Save'
 

app/views/wikis/edit.html.slim
h1 Editing wiki

== render 'form'

= link_to 'Show', @wiki
'|
= link_to 'Back', wikis_path

app/views/wikis/index.html.slim
h1 Public wikis

table
  thead
    tr
      th Wiki Title
      th Wiki Body
      th Wiki Owner

  tbody
    - @public_wikis.each do |wiki|
      tr
        td = link_to wiki.title, wiki
        td = wiki.body
        td = wiki.user_id

br
br
- if user_signed_in?
  h2 My Private wikis
  table
    thead
      tr
        th Title
        th Body
        th Owner

    tbody
      - @private_wikis.each do |wiki| 
        tr
          td = link_to wiki.title, wiki
          td = wiki.body
          td = wiki.user_id
  br
  br

- if user_signed_in?
  h2 Wikis shared with me
  table
    thead
      tr
        th Wiki Title
        th Wiki Body 
        th Wiki Owner
    tbody
      - @collaboration_wikis.each do |wiki_name|
        tr
          td = link_to wiki_name.title, wiki_name
          td = wiki_name.body
          td = wiki_name.user_id
<br/>
<br/>

= link_to 'New Wiki', new_wiki_path if user_signed_in?
br
= link_to 'Upgrade to premium account', new_charge_path if user_signed_in?

app/views/wikis/new.html.slim
h1 New wiki

== render 'form'

= link_to 'Back', wikis_path

app/views/wikis/show.html.slim
p#notice = notice

p
  strong Title:
  = @wiki.title
p
  strong Body:
  = @wiki.body

= link_to 'Edit', edit_wiki_path(@wiki)
'|
= link_to 'Back', wikis_path